# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: /ide-desktop/backend/bin/remote-dev-server.sh installPlugins . 14590-gwt
  - init: /ide-desktop/backend/bin/remote-dev-server.sh warm-up .